spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/web_walker
    username: zogoo
    password: admin
host:
  url: "http://www.google.com"
client:
  agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36"
  timeout: 5000
  cookie: "value123"
  refferer: "http://google.com"
  header: "xyz123"
flyway:
  baseline-on-migrate: true